# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3b14aceb5372ceeab09f2ea486e190b3a110915374c3733b5f291d5c2714675c24e3608b1e4946494988cbd6e763cf0a39e8b5e737b6cbdf74902c44846f50f

test:
  secret_key_base: a848777e7b8f0370fe878901132e0598ebb475566418a3d05542f013baec857cb636c0b4420c54c36e2b521cfd10ba0f8649e514a0ae4e9cd8024990db4b05a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
